### ISSUE TITLE
PlatformIO 4 breaking changes

### ISSUE THREAD

**Issue by Kernald** [mum4k/platformio_rules#14]
PlatformIO 4 has been released, and includes some breaking changes: https://docs.platformio.org/en/latest/migration.html

It might be interesting to pin a specific PlatformIO version from those rules and download it when needed, rather than relying on a system-provided version.

**Comment by mum4k** [comment]
Thank you for reporting this. Reading the linked guide, looks like only the location of the firmware was changed.

Agreed that pinning to a specific version is a good idea. Is thins something you would be able to send a PR for?

**Comment by Kernald** [comment]
I would be happy to, but won't have any time to do it in the near future. (And I also have no idea how Python works, and even less its packaging/deployment, but that's secondary)

**Comment by mum4k** [comment]
Looks like we can easily fix this by adjusting the path of the expected firmware (#15). We can still consider pinning if this starts happening more often. 

Note as before - I no longer have a board so I cannot verify that uploading works after this fix. However it should since upload is fully handled by Platformio itself.
