### ISSUE TITLE
`platformio` binary is not always in `/usr/local/bin/`

### ISSUE THREAD

**Issue by Kernald** [mum4k/platformio_rules#5]
On Archlinux, when installing PlatformIO from AUR, the binary ends up in `/usr/bin/platformio`. The rules should either allow to specify an alternative path, or look in `$PATH`.

**Comment by mum4k** [comment]
This should work better now, instead of looking at specific paths, all commands are now retrieved from the PATH env variable.

It isn't the user's PATH variable though, it is one defined here:
https://github.com/mum4k/platformio_rules/blob/1225cd79fb93d5681323fcea41a404e03a51e15f/platformio/platformio.bzl#L202

Please let me know if this didn't help.
