### ISSUE TITLE
Firmware file extension depend on the platform

### ISSUE THREAD

**Issue by Kernald** [mum4k/platformio_rules#6]
Targeting the platform `espressif8266`, the firmware is not found by the rule:

```
Linking .pioenvs/nodemcuv2/firmware.elf
Retrieving maximum program size .pioenvs/nodemcuv2/firmware.elf
Checking size .pioenvs/nodemcuv2/firmware.elf
Building .pioenvs/nodemcuv2/firmware.bin
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [====      ]  35.3% (used 28896 bytes from 81920 bytes)
PROGRAM: [===       ]  27.3% (used 285068 bytes from 1044464 bytes)
========================= [SUCCESS] Took 4.51 seconds =========================
ERROR: /.../BUILD:12:1: output '.pioenvs/nodemcuv2/firmware.hex' was not created
```

It's apparently named `firmware.bin` rather than `firmware.hex`.

**Comment by Kernald** [comment]
As a sanity check, I replaced `hex` by `bin` [here](https://github.com/mum4k/platformio_rules/blob/master/platformio/platformio.bzl#L345) in a local copy of the rules, it worked perfectly (at least the build, I don't have a board nearby to actually test the deployment). I'm not sure what would be the best way of discovering the correct extension, maybe try a predefined list? (I never wrote any Bazel rule so I'm not sure what is possible or not when defining the outputs)

**Comment by mum4k** [comment]
Thank you for the bug report, I will see what can be done.

**Comment by mum4k** [comment]
Turns out the simplest solution is to just remove that file from the predeclared outputs. Its only purpose for being there was to somehow verify that platformio did its thing and compiled the code.

That is still verified by getting the zero exit code from platformio and by the existence of the firmware.elf file.

Sadly I no longer have a board at home, so cannot completely verify it, but the tests seem to be happy. I would appreciate if you could test this with a board and let me know if this broke something.

**Comment by Kernald** [comment]
Seems to be working fine, I successfully deployed to a nodemcuv2 board. Thanks!

**Comment by mum4k** [comment]
Great, thanks a lot for confirming!
